# Generated by Django 4.2.16 on 2024-11-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sitters", "0002_initial"),
        ("clients", "0004_fix_pet_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("pet_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "profile_photo",
                    models.ImageField(blank=True, null=True, upload_to="pet_photos/"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("DOG", "Dog"),
                            ("CAT", "Cat"),
                            ("BIRD", "Bird"),
                            ("FISH", "Fish"),
                            ("REPTILE", "Reptile"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("age", models.IntegerField()),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("special_needs", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="clients.client",
                    ),
                ),
                (
                    "sitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cared_pets",
                        to="sitters.sitter",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
