# Generated by Django 4.2.16 on 2024-11-22 15:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="special_needs",
            new_name="special_care_instructions",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="age",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="client",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="sitter",
        ),
        migrations.AddField(
            model_name="pet",
            name="adoption_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="age_months",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(11),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="age_years",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="can_be_left_alone",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="energy_level",
            field=models.CharField(
                blank=True,
                choices=[("LOW", "Low"), ("MODERATE", "Moderate"), ("HIGH", "High")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="feeding_schedule",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="friendly_with_cats",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="friendly_with_children",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="friendly_with_dogs",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="house_trained",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="insurance_provider",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pet",
            name="medication_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="medications",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="pet",
            name="microchipped",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_pets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="pet_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="pet_type",
            field=models.CharField(
                blank=True, help_text="Specific type for exotic pets", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="photo_gallery",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pet",
            name="potty_break_schedule",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="spayed_neutered",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="vet_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="vet_documents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pet",
            name="vet_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pet",
            name="vet_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
