# Generated by Django 4.2.16 on 2025-01-13 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("professionals", "0001_initial"),
        ("clients", "0003_alter_client_authorized_household_members_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("service_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "PENDING_INITIAL_PROFESSIONAL_CHANGES",
                                "Pending Initial Professional Changes",
                            ),
                            (
                                "PENDING_PROFESSIONAL_CHANGES",
                                "Pending Professional Changes",
                            ),
                            ("PENDING_CLIENT_APPROVAL", "Pending Client Approval"),
                            (
                                "CONFIRMED_PENDING_PROFESSIONAL_CHANGES",
                                "Confirmed Pending Professional Changes",
                            ),
                            ("CONFIRMED", "Confirmed"),
                            ("DENIED", "Denied"),
                            ("CANCELLED", "Cancelled"),
                            ("DRAFT", "Draft"),
                        ],
                        max_length=100,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_client_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_sitter_payout",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client"
                    ),
                ),
                (
                    "denied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="denied_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professionals.professional",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
