# Generated by Django 4.2.16 on 2024-10-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
