# Generated by Django 4.2.16 on 2024-10-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="last_booking",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="pet_types",
            field=models.JSONField(default=list),
        ),
    ]
