name: Deploy Staging (MVP → gh-pages-test)

on:
  push:
    branches:
      - mvp   # Triggers on push to the mvp branch
  workflow_dispatch: # Allows manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        working-directory: ZenExoticsMobile  # ✅ Set correct directory for npm
        run: |
          npm install --legacy-peer-deps
          npm run build:staging

      - name: Create CNAME for Staging
        working-directory: ZenExoticsMobile/web-build  # ✅ Set correct directory for CNAME
        run: echo "staging.crittrcove.com" > CNAME

      - name: Deploy to GitHub Pages (Staging)
        working-directory: ZenExoticsMobile  # ✅ Run deployment from the correct folder
        run: npm run deploy:staging
