name: Deploy Staging (MVP → gh-pages-test)

on:
  push:
    branches:
      - mvp   # Triggers on push to the mvp branch
  workflow_dispatch: # Allows manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        working-directory: ZenExoticsMobile  # ✅ Set correct directory for npm
        run: |
          npm install --legacy-peer-deps
          npm run build:staging  # ✅ This builds the `web-build` directory

      - name: Create CNAME for Staging
        working-directory: ZenExoticsMobile/web-build  # ✅ Ensure correct path
        run: echo "staging.crittrcove.com" > CNAME

      - name: "Debug: Check if web-build exists"
        run: |
          ls -al ZenExoticsMobile/web-build || echo "web-build directory is missing!"

      - name: Deploy to GitHub Pages (Staging)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ZenExoticsMobile/web-build
          publish_branch: gh-pages-test
          force_orphan: true  # ✅ Forces a fresh commit every time

