name: Deploy Staging (MVP → gh-pages-test)

on:
  push:
    branches:
      - mvp   # Triggers on push to the mvp branch
  workflow_dispatch: # Allows manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        working-directory: ZenExoticsMobile  # ✅ Change from 'frontend' to 'ZenExoticsMobile'
        run: |
          npm install --legacy-peer-deps  # ✅ Fix dependency resolution
          npm run build:staging

      - name: Create CNAME for Staging
        run: echo "staging.crittrcove.com" > ZenExoticsMobile/web-build/CNAME  # ✅ Correct path

      - name: Deploy to GitHub Pages (Staging)
        run: npm run deploy:staging
