name: Deploy Production (Main → gh-pages)

on:
  push:
    branches:
      - prototype  # Once MVP is stable, main will be the production trigger
  workflow_dispatch: # Allows manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        working-directory: ZenExoticsMobile
        run: |
          npm install --legacy-peer-deps
          npm run build  # Runs the build script from package.json

      - name: Create CNAME for Production
        run: echo "crittrcove.com" > ZenExoticsMobile/web-build/CNAME  # Ensure production domain is set

      - name: Deploy to GitHub Pages (Production)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ZenExoticsMobile/web-build  # Production output
          publish_branch: gh-pages  # Production branch
